image:
  file: .gitpod.Dockerfile

tasks:
  - command: pwsh

vscode:
  extensions:
    - ms-vscode.powershell-preview

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
#ports:
#  - port: 3000
#    onOpen: open-preview
